### ISSUE TITLE
AmateursCTF writeups, currently ongoing

### ISSUE THREAD

**Issue by stuxf** [wblazej/ctf-writeups#1]
Hey, you have writeups for AmateursCTF 2023 which is a currently ongoing competition. Please remove them and [clear from git history](https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/removing-sensitive-data-from-a-repository), or make the repository private.

We (the organizer team) would appreciate if you could remove these writeups.

Thank you.

**Comment by wblazej** [comment]
Hey, thank you for reaching out. I didn't realize the competition was not over, my mistake. I removed writeups for AmateursCTF 2023. I'm sorry about that. Hope it didn't disturb the competition as much.

Thank you
